name: Run Script on New Commit
on:
  push:
    branches:
      - master
jobs:
  execute-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout RepoA
        uses: actions/checkout@v2
        with:
          repository: truskmsarih/repodeux
          token: ${{ secrets.REPOA_ACCESS_TOKEN }}
          
      - name: Run Script
        run: |
          echo "Hello world"
